# Generated by Django 4.2.7 on 2023-11-25 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_student_student_department_id_school_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 14, 23, 3, 292072)),
        ),
    ]
